config/routes.rb
Rails.application.routes.draw do
  resources :notes
  resources :course_tags
  resources :subjects
  resources :courses
  root 'web#index'
  get 'web/index'
  get 'web/tut'
  devise_for :users
end

app/models/course_tag.rb
class CourseTag < ApplicationRecord
end

app/controllers/course_tags_controller.rb
class CourseTagsController < ApplicationController
  before_action :set_course_tag, only: [:show, :edit, :update, :destroy]

  # GET /course_tags
  # GET /course_tags.json
  def index
    @course_tags = CourseTag.all
  end

  # GET /course_tags/1
  # GET /course_tags/1.json
  def show
  end

  # GET /course_tags/new
  def new
    @course_tag = CourseTag.new
  end

  # GET /course_tags/1/edit
  def edit
  end

  # POST /course_tags
  # POST /course_tags.json
  def create
    @course_tag = CourseTag.new(course_tag_params)

    respond_to do |format|
      if @course_tag.save
        format.html { redirect_to @course_tag, notice: 'Course tag was successfully created.' }
        format.json { render :show, status: :created, location: @course_tag }
      else
        format.html { render :new }
        format.json { render json: @course_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /course_tags/1
  # PATCH/PUT /course_tags/1.json
  def update
    respond_to do |format|
      if @course_tag.update(course_tag_params)
        format.html { redirect_to @course_tag, notice: 'Course tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @course_tag }
      else
        format.html { render :edit }
        format.json { render json: @course_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_tags/1
  # DELETE /course_tags/1.json
  def destroy
    @course_tag.destroy
    respond_to do |format|
      format.html { redirect_to course_tags_url, notice: 'Course tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course_tag
      @course_tag = CourseTag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_tag_params
      params.require(:course_tag).permit(:course, :subject, :is_active)
    end
end

app/helpers/course_tags_helper.rb
module CourseTagsHelper
end

app/views/course_tags/_form.html.erb
<%@course=Course.select(:course)
@subject = Subject.select(:subject)%>
<%= form_with(model: course_tag, local: true) do |form| %>
  <% if course_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course_tag.errors.count, "error") %> prohibited this course_tag from being saved:</h2>

      <ul>
        <% course_tag.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :course %>
    <%= form.select(:course, @course.collect{|c| [c.course]}, {include_blank: "--Select A Course--"}, :class => 'w3-input')%>
  </div>

  <div class="field">
    <%= form.label :subject %>
    <%= form.select(:subject, @subject.collect{|s| [s.subject]}, {include_blank: "--Select A Subject--"}, :class => 'w3-input')%>
  </div>

  <div class="field">
    <%= form.label :is_active %>
    <%= form.check_box :is_active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/course_tags/edit.html.erb
<h1>Editing Course Tag</h1>

<%= render 'form', course_tag: @course_tag %>

<%= link_to 'Show', @course_tag %> |
<%= link_to 'Back', course_tags_path %>

app/views/course_tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Course Tags</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Subject</th>
      <th>Is active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @course_tags.each do |course_tag| %>
      <tr>
        <td><%= course_tag.course %></td>
        <td><%= course_tag.subject %></td>
        <td><%= course_tag.is_active %></td>
        <td><%= link_to 'Show', course_tag %></td>
        <td><%= link_to 'Edit', edit_course_tag_path(course_tag) %></td>
        <td><%= link_to 'Destroy', course_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course Tag', new_course_tag_path %>

app/views/course_tags/new.html.erb
<h1>New Course Tag</h1>

<%= render 'form', course_tag: @course_tag %>

<%= link_to 'Back', course_tags_path %>

app/views/course_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @course_tag.course %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @course_tag.subject %>
</p>

<p>
  <strong>Is active:</strong>
  <%= @course_tag.is_active %>
</p>

<%= link_to 'Edit', edit_course_tag_path(@course_tag) %> |
<%= link_to 'Back', course_tags_path %>